# Generated by Django 5.2.17 on 2026-08-31 06:44

import apps.subscriptions.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_plans'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('manual_bank_transfer', 'واریز بانکی دستی'), ('bank_gateway', 'درگاه بانکی')], default='manual_bank_transfer', max_length=30)),
                ('amount_snapshot', models.DecimalField(decimal_places=2, max_digits=18)),
                ('status', models.CharField(choices=[('pending_submission', 'در انتظار ثبت اطلاعات'), ('pending_review', 'در انتظار بررسی پرداخت'), ('approved', 'پرداخت تأیید شده'), ('rejected', 'پرداخت رد شده'), ('cancelled', 'لغو شده')], default='pending_review', max_length=20)),
                ('payer_name', models.CharField(blank=True, max_length=150)),
                ('payer_card_last4', models.CharField(blank=True, max_length=4)),
                ('tracking_code', models.CharField(blank=True, max_length=100)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_image', models.FileField(blank=True, upload_to=apps.subscriptions.models.receipt_upload_path)),
                ('user_note', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('gateway', models.CharField(blank=True, max_length=50)),
                ('gateway_authority', models.CharField(blank=True, max_length=150)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_subscription_payments', to=settings.AUTH_USER_MODEL)),
                ('subscription_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='subscriptions.subscriptionorder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status', 'created_at'], name='subscriptio_status_9569df_idx'), models.Index(fields=['user', 'created_at'], name='subscriptio_user_id_a1e4d8_idx')],
            },
        ),
    ]
