# Generated by Django 5.2.17 on 2026-08-31 08:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_subscriptionpayment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ویزیت\u200cیار', max_length=100)),
                ('short_description', models.CharField(blank=True, max_length=300)),
                ('manual_payment_enabled', models.BooleanField(default=True)),
                ('account_holder', models.CharField(blank=True, max_length=150)),
                ('card_number', models.CharField(blank=True, max_length=30)),
                ('iban', models.CharField(blank=True, max_length=34)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('payment_instructions', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'platform settings',
            },
        ),
        migrations.CreateModel(
            name='PlatformAdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('target_type', models.CharField(max_length=60)),
                ('target_id', models.CharField(blank=True, max_length=64)),
                ('target_display', models.CharField(blank=True, max_length=200)),
                ('before_snapshot', models.JSONField(blank=True, default=dict)),
                ('after_snapshot', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_admin_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
