# Generated by Django 5.2.17 on 2026-09-04 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_plan_discounts_order_snapshots_and_repair'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='source',
            field=models.CharField(choices=[('paid', 'اشتراک پولی'), ('free_trial', 'آزمایش رایگان'), ('manual', 'فعال\u200cسازی دستی')], default='paid', max_length=12),
        ),
    ]
