# Generated by Django 5.2.17 on 2026-09-04 22:02

from django.db import migrations, models


def rename_existing_brand(apps, schema_editor):
    PlatformSettings = apps.get_model("subscriptions", "PlatformSettings")
    PlatformSettings.objects.filter(site_name__in=("ویزیت‌یار", "ویزیت یار", "ویزیتیار")).update(site_name="ویزیتورکار")


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_usersubscription_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platformsettings',
            name='site_name',
            field=models.CharField(default='ویزیتورکار', max_length=100),
        ),
        migrations.RunPython(rename_existing_brand, migrations.RunPython.noop),
    ]
