# Generated by Django 5.2.17 on 2026-08-29 12:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='شماره تماس واردشده معتبر نیست.', regex='^[0-9+()\\-\\s]{7,25}$')])),
                ('address', models.CharField(blank=True, max_length=500)),
                ('economic_code', models.CharField(blank=True, max_length=30)),
                ('national_id', models.CharField(blank=True, max_length=30)),
                ('registration_number', models.CharField(blank=True, max_length=30)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['owner', 'is_active'], name='companies_s_owner_i_26633e_idx'), models.Index(fields=['owner', 'name'], name='companies_s_owner_i_cc9b46_idx')],
            },
        ),
    ]
