# Generated by Django 5.2.17 on 2026-09-02 09:00

import apps.companies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='signature_image',
            field=models.FileField(blank=True, upload_to=apps.companies.models.seller_asset_path),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='stamp_image',
            field=models.FileField(blank=True, upload_to=apps.companies.models.seller_asset_path),
        ),
    ]
