import { useEffect, useState } from "react";
import { navigate } from "../hooks/useRoute";
import { useAuth } from "../services/AuthContext";
import { listPlans } from "../services/subscriptions";
import { formatPrice } from "../services/products";

const features = [
  ["محصول و مشتری", "اطلاعات محصولات و مشتریان را مرتب، سریع و همیشه در دسترس نگه دارید."],
  ["سفارش و خرید", "سفارش فروش و خرید را همان لحظه و با تجربه‌ای مناسب موبایل ثبت کنید."],
  ["فاکتور PDF", "فاکتور فارسی حرفه‌ای صادر کنید و اصلاحات آن را با نسخه‌بندی دقیق نگه دارید."],
  ["مرجوعی و موجودی", "مرجوعی‌ها و گردش موجودی را بدون حذف تاریخچه کسب‌وکار مدیریت کنید."],
  ["داشبورد و گزارش", "فروش، خرید، مرجوعی و عملکرد محصولات و مشتریان را یک‌جا ببینید."],
  ["نصب روی موبایل", "سامانه را به‌صورت PWA روی موبایل نصب کنید و سریع به آن برگردید."],
];

export default function LandingPage() {
  const { user } = useAuth();
  const [plans, setPlans] = useState([]);
  useEffect(() => { listPlans().then(setPlans).catch(() => {}); }, []);
  const start = () => navigate(user ? "/pricing" : "/register");
  return <main className="min-h-dvh w-screen max-w-[100vw] overflow-x-hidden bg-[#f7faf9] text-slate-900">
    <header className="sticky top-0 z-40 w-screen max-w-[100vw] overflow-hidden border-b border-emerald-950/10 bg-[#f7faf9]/90 backdrop-blur"><nav className="mx-auto flex min-h-18 w-screen max-w-7xl items-center justify-between gap-2 px-4 sm:px-6"><button className="flex shrink-0 items-center gap-2 text-lg font-black" onClick={() => navigate("/")}><span className="grid size-9 place-items-center rounded-xl bg-emerald-800 text-white">و</span><span className="hidden sm:inline">ویزیت‌یار</span></button><div className="hidden items-center gap-7 text-sm font-semibold md:flex"><a href="#features">امکانات</a><a href="#pricing">تعرفه‌ها</a><a href="#about">درباره محصول</a></div><div className="flex shrink-0 items-center gap-1 sm:gap-2"><button className="min-h-11 px-2 text-sm font-bold sm:px-3" onClick={() => navigate(user ? "/app" : "/login")}>{user ? "پنل" : "ورود"}</button><button className="min-h-11 rounded-xl bg-emerald-800 px-3 text-sm font-bold text-white sm:px-4" onClick={start}>شروع استفاده</button></div></nav></header>
    <section className="relative mx-auto grid w-screen max-w-7xl overflow-hidden gap-10 px-4 py-16 sm:px-6 lg:grid-cols-2 lg:items-center lg:py-24"><div className="min-w-0"><p className="mb-5 inline-block max-w-full rounded-2xl border border-emerald-200 bg-emerald-50 px-3 py-2 text-xs font-bold leading-6 text-emerald-800 sm:rounded-full sm:px-4 sm:text-sm">سامانه فروش میدانی برای کسب‌وکارهای ایرانی</p><h1 className="break-words text-3xl font-black leading-[1.45] sm:text-5xl lg:text-6xl">فروش، فاکتور، مشتری و موجودی؛ <span className="text-emerald-700">در یک پنل سریع</span></h1><p className="mt-6 max-w-2xl text-base leading-8 text-slate-600 sm:text-lg sm:leading-9">برای ویزیتورها و تیم‌های فروش که می‌خواهند هنگام گفت‌وگو با مشتری، سفارش را سریع ثبت کنند و تصویر دقیقی از کسب‌وکار داشته باشند.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button className="min-h-14 rounded-2xl bg-emerald-800 px-7 font-bold text-white shadow-lg shadow-emerald-900/15" onClick={start}>شروع استفاده</button><a className="grid min-h-14 place-items-center rounded-2xl border border-slate-300 px-7 font-bold" href="#features">مشاهده امکانات</a></div></div><div className="min-w-0 overflow-hidden rounded-[2rem] bg-gradient-to-br from-emerald-900 to-teal-700 p-4 shadow-2xl shadow-emerald-950/20 sm:p-5"><div className="rounded-2xl bg-white/95 p-4 sm:p-5"><div className="flex items-center justify-between gap-2"><div className="min-w-0"><p className="text-sm text-slate-500">نمای امروز</p><p className="mt-1 text-lg font-black sm:text-xl">داشبورد کسب‌وکار</p></div><span className="shrink-0 rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">به‌روز</span></div><div className="mt-5 grid grid-cols-2 gap-3">{["فروش امروز","سفارش‌ها","فاکتورهای صادرشده","موجودی"].map((x,i)=><div className="min-w-0 rounded-2xl bg-slate-50 p-3 sm:p-4" key={x}><p className="truncate text-xs text-slate-500">{x}</p><div className="mt-3 h-3 rounded-full bg-slate-200"><div className="h-3 rounded-full bg-emerald-600" style={{width:`${55+i*10}%`}} /></div></div>)}</div></div></div></section>
    <section className="border-y border-slate-200 bg-white py-16" id="features"><div className="mx-auto max-w-7xl px-4 sm:px-6"><div className="max-w-2xl"><p className="font-bold text-emerald-700">امکانات واقعی، برای کار روزمره</p><h2 className="mt-3 text-3xl font-black">از اولین سفارش تا گزارش نهایی</h2></div><div className="mt-9 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(([title,text],i)=><article className="rounded-2xl border border-slate-200 p-6 transition hover:-translate-y-1 hover:shadow-lg" key={title}><span className="grid size-10 place-items-center rounded-xl bg-emerald-100 font-black text-emerald-800">{i+1}</span><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-2 leading-7 text-slate-600">{text}</p></article>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-16 sm:px-6" id="about"><div className="rounded-[2rem] bg-slate-900 px-6 py-10 text-white sm:p-12"><p className="text-emerald-300">شروع ساده و شفاف</p><h2 className="mt-2 text-3xl font-black">چهار قدم تا مدیریت منظم فروش</h2><div className="mt-8 grid gap-5 md:grid-cols-4">{["ساخت حساب","انتخاب اشتراک","ثبت اطلاعات کسب‌وکار","شروع فروش و صدور فاکتور"].map((x,i)=><div key={x}><span className="text-3xl font-black text-emerald-400">۰{i+1}</span><p className="mt-3 font-bold">{x}</p></div>)}</div></div></section>
    <section className="bg-emerald-950 py-16 text-white" id="pricing"><div className="mx-auto max-w-5xl px-4 sm:px-6"><div className="text-center"><p className="font-bold text-emerald-300">تعرفه‌های قابل ویرایش</p><h2 className="mt-3 text-3xl font-black">اشتراک متناسب با زمان شما</h2></div><div className="mt-9 grid gap-5 md:grid-cols-2">{plans.map(plan=><article className={`rounded-3xl border p-7 ${plan.is_featured?"border-emerald-300 bg-white text-slate-900":"border-white/20 bg-white/5"}`} key={plan.id}>{plan.is_featured&&<span className="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">پیشنهاد ویژه</span>}<h3 className="mt-4 text-2xl font-black">{plan.name}</h3><p className="mt-2 opacity-70">{plan.description}</p><p className="mt-7 text-3xl font-black">{formatPrice(plan.price)}</p><p className="mt-2 text-sm opacity-70">{plan.duration_days} روز دسترسی</p><button className="mt-7 min-h-12 w-full rounded-xl bg-emerald-600 font-bold text-white" onClick={start}>انتخاب اشتراک</button></article>)}</div></div></section>
    <section className="mx-auto max-w-4xl px-4 py-16 sm:px-6"><h2 className="text-center text-3xl font-black">پرسش‌های متداول</h2><div className="mt-8 space-y-3">{[["آیا اطلاعات من محفوظ است؟","دسترسی هر کاربر از دیگر کاربران جداست و کنترل دسترسی در سرور اجرا می‌شود."],["آیا روی موبایل کار می‌کند؟","بله؛ رابط کاربری موبایل‌محور است و به‌صورت PWA نیز نصب می‌شود."],["آیا فاکتور PDF دارد؟","بله؛ فاکتور فارسی PDF با نسخه‌بندی اصلاحات قابل دریافت است."],["اگر اشتراک تمام شود چه می‌شود؟","اطلاعات شما محفوظ می‌ماند؛ فقط عملیات کسب‌وکار تا تمدید اشتراک متوقف می‌شود."]].map(([q,a])=><details className="rounded-2xl border border-slate-200 bg-white p-5" key={q}><summary className="cursor-pointer font-bold">{q}</summary><p className="mt-3 leading-7 text-slate-600">{a}</p></details>)}</div></section>
    <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-4 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between"><strong className="text-slate-900">ویزیت‌یار</strong><div className="flex gap-5"><button onClick={()=>navigate("/pricing")}>تعرفه‌ها</button><button onClick={()=>navigate("/login")}>ورود</button></div><span>محصول مدیریت فروش میدانی</span></div></footer>
  </main>;
}
