# Generated by Django 5.2.17 on 2026-08-29 13:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        ('orders', '0001_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('issued', 'صادرشده'), ('cancelled', 'لغوشده'), ('superseded', 'جایگزین\u200cشده')], default='issued', max_length=12)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('seller_name', models.CharField(max_length=200)),
                ('seller_phone_number', models.CharField(blank=True, max_length=25)),
                ('seller_address', models.CharField(blank=True, max_length=500)),
                ('seller_economic_code', models.CharField(blank=True, max_length=30)),
                ('seller_national_id', models.CharField(blank=True, max_length=30)),
                ('seller_registration_number', models.CharField(blank=True, max_length=30)),
                ('seller_postal_code', models.CharField(blank=True, max_length=20)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_company_name', models.CharField(blank=True, max_length=200)),
                ('buyer_phone_number', models.CharField(blank=True, max_length=25)),
                ('buyer_address', models.CharField(blank=True, max_length=500)),
                ('buyer_economic_code', models.CharField(blank=True, max_length=30)),
                ('buyer_postal_code', models.CharField(blank=True, max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('duties_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
                ('sales_order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='orders.salesorder')),
                ('seller_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='companies.sellerprofile')),
            ],
            options={
                'ordering': ('-issued_at',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=18)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='products.product')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['owner', 'issued_at'], name='invoices_in_owner_i_67d935_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('owner', 'invoice_number'), name='unique_owner_invoice_number'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'issued')), fields=('sales_order',), name='one_issued_invoice_per_order'),
        ),
    ]
