# Generated by Django 5.2.17 on 2026-09-02 09:00

import apps.invoices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_revisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='signature_snapshot',
            field=models.FileField(blank=True, upload_to=apps.invoices.models.invoice_asset_path),
        ),
        migrations.AddField(
            model_name='invoice',
            name='stamp_snapshot',
            field=models.FileField(blank=True, upload_to=apps.invoices.models.invoice_asset_path),
        ),
    ]
