# Generated by Django 5.2.17 on 2026-09-04 17:30

import apps.support.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_staff_reply', models.BooleanField(default=False)),
                ('is_internal_note', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='SupportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.support.models.support_upload_path)),
                ('original_name', models.CharField(max_length=180)),
                ('content_type', models.CharField(max_length=80)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='support.supportmessage')),
            ],
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(editable=False, max_length=16, unique=True)),
                ('subject', models.CharField(max_length=180)),
                ('category', models.CharField(choices=[('technical', 'مشکل فنی'), ('usage', 'سوال درباره استفاده از سامانه'), ('order_invoice', 'سفارش و فاکتور'), ('data', 'اطلاعات و داده\u200cها'), ('subscription', 'اشتراک و پرداخت'), ('account', 'حساب کاربری'), ('feedback', 'پیشنهاد و بازخورد'), ('other', 'سایر')], max_length=24)),
                ('priority', models.CharField(choices=[('low', 'کم'), ('normal', 'عادی'), ('high', 'مهم')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال بررسی'), ('waiting_for_customer', 'در انتظار پاسخ شما'), ('resolved', 'حل شده'), ('closed', 'بسته شده')], default='open', max_length=24)),
                ('context_type', models.CharField(blank=True, max_length=20)),
                ('context_id', models.CharField(blank=True, max_length=64)),
                ('context_label', models.CharField(blank=True, max_length=180)),
                ('customer_unread', models.BooleanField(default=False)),
                ('admin_unread', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_admin', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_tickets', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-admin_unread', '-last_message_at'),
            },
        ),
        migrations.AddField(
            model_name='supportmessage',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportticket'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['status', 'last_message_at'], name='support_sup_status_9a3572_idx'),
        ),
        migrations.AddIndex(
            model_name='supportticket',
            index=models.Index(fields=['user', 'last_message_at'], name='support_sup_user_id_06bfc2_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['ticket', 'created_at'], name='support_sup_ticket__8eea9f_idx'),
        ),
    ]
