import { Component, useState } from "react";
import { navigate } from "../../hooks/useRoute";
import { useAuth } from "../../services/AuthContext";

export const statusLabels={pending:"در انتظار پرداخت کاربر",pending_review:"در انتظار بررسی پرداخت",pending_submission:"در انتظار ثبت پرداخت",approved:"تأیید شده",active:"فعال",expired:"منقضی",rejected:"پرداخت رد شده",cancelled:"لغو شده",inactive:"غیرفعال"};
export function StatusBadge({value}){const good=["active","approved"].includes(value),wait=["pending","pending_review","pending_submission"].includes(value);return <span className={`inline-flex rounded-full px-3 py-1 text-xs font-bold ${good?"bg-emerald-100 text-emerald-800":wait?"bg-amber-100 text-amber-800":value==="rejected"?"bg-red-100 text-red-700":"bg-slate-100 text-slate-700"}`}>{statusLabels[value]||value}</span>}
const links=[["/platform-admin","داشبورد"],["/platform-admin/support","پشتیبانی"],["/platform-admin/users","کاربران"],["/platform-admin/subscription-orders","درخواست‌های اشتراک"],["/platform-admin/payments","پرداخت‌ها"],["/platform-admin/subscriptions","اشتراک‌ها"],["/platform-admin/plans","پلن‌های اشتراک"],["/platform-admin/settings","تنظیمات سامانه"],["/platform-admin/audit-log","گزارش فعالیت مدیران"]];
export function AdminLayout({title,subtitle,children}){const {user,logout}=useAuth();const [open,setOpen]=useState(false);const path=window.location.pathname;return <main className="min-h-dvh bg-slate-100 text-slate-900 lg:pr-72"><button className="fixed right-4 top-4 z-40 grid h-11 w-11 place-items-center rounded-xl bg-slate-950 text-xl text-white lg:hidden" onClick={()=>setOpen(true)} aria-label="باز کردن منو">☰</button>{open&&<button className="fixed inset-0 z-40 bg-slate-950/50 lg:hidden" onClick={()=>setOpen(false)} aria-label="بستن منو"/>}<aside className={`fixed inset-y-0 right-0 z-50 w-72 bg-slate-950 p-5 text-white transition-transform lg:translate-x-0 ${open?"translate-x-0":"translate-x-full"}`}><div className="flex items-start justify-between border-b border-slate-800 pb-5"><div><p className="text-xs font-bold text-emerald-300">کنترل پنل پلتفرم</p><h1 className="mt-1 text-2xl font-black">ویزیت‌یار</h1></div><button className="text-slate-400 lg:hidden" onClick={()=>setOpen(false)}>✕</button></div><nav className="mt-6 space-y-2">{links.map(([url,label])=>{const active=url==="/platform-admin"?path===url:path.startsWith(url);return <button key={url} className={`min-h-12 w-full rounded-xl px-4 text-right font-bold ${active?"bg-emerald-600 text-white":"text-slate-300 hover:bg-slate-800"}`} onClick={()=>{setOpen(false);navigate(url)}}>{label}</button>})}</nav><button className="absolute bottom-6 right-5 left-5 min-h-11 rounded-xl border border-slate-700 text-slate-300" onClick={()=>{logout();navigate("/")}}>خروج از حساب</button></aside><section className="min-w-0 p-4 pt-20 sm:p-7 sm:pt-20 lg:p-9"><header className="mb-7 flex flex-col gap-2 border-b border-slate-200 pb-6 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="text-2xl font-black sm:text-3xl">{title}</h2>{subtitle&&<p className="mt-2 text-sm text-slate-500">{subtitle}</p>}</div><p className="text-sm text-slate-500" dir="ltr">{user?.email}</p></header>{children}</section></main>}
export function StateBox({loading,error,empty,retry}){if(loading)return <div className="rounded-2xl bg-white p-10 text-center text-slate-500">در حال دریافت اطلاعات…</div>;if(error)return <div className="rounded-2xl bg-red-50 p-5 text-red-700"><p>{error}</p>{retry&&<button className="admin-button mt-4 bg-white" onClick={retry}>تلاش مجدد</button>}</div>;if(empty)return <div className="rounded-2xl bg-white p-10 text-center text-slate-500">موردی برای نمایش وجود ندارد.</div>;return null}
export function Pagination({data,onPage}){if(!data||data.count<=20)return null;return <div className="mt-5 flex items-center justify-center gap-3"><button className="admin-button" disabled={!data.previous} onClick={()=>onPage(-1)}>قبلی</button><span className="text-sm text-slate-600">{data.count} مورد</span><button className="admin-button" disabled={!data.next} onClick={()=>onPage(1)}>بعدی</button></div>}
export function ConfirmDialog({open,title,description,requireReason,onCancel,onConfirm,busy}){const [reason,setReason]=useState("");if(!open)return null;return <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/60 p-4"><section className="w-full max-w-md rounded-3xl bg-white p-6"><h3 className="text-xl font-black">{title}</h3><p className="mt-2 text-sm leading-7 text-slate-600">{description}</p>{requireReason&&<textarea className="admin-input mt-4 min-h-28 w-full py-3" placeholder="دلیل رد را وارد کنید" value={reason} onChange={e=>setReason(e.target.value)}/>}<div className="mt-5 flex gap-3"><button className="admin-button flex-1" onClick={onCancel}>انصراف</button><button disabled={busy||(requireReason&&!reason.trim())} className="admin-button flex-1 border-0 bg-emerald-700 text-white disabled:opacity-50" onClick={()=>onConfirm(reason.trim())}>تأیید نهایی</button></div></section></div>}

export class AdminErrorBoundary extends Component {
  constructor(props){super(props);this.state={failed:false}}
  static getDerivedStateFromError(){return {failed:true}}
  componentDidCatch(error,info){if(import.meta.env.DEV)console.error("Platform admin render error",error,info)}
  render(){if(this.state.failed)return <AdminLayout title="خطای نمایش پنل"><div className="rounded-2xl bg-white p-6 ring-1 ring-red-200"><h3 className="text-lg font-black text-red-700">خطایی در نمایش پنل مدیریت رخ داد.</h3><p className="mt-2 text-sm leading-7 text-slate-600">اطلاعات شما تغییری نکرده است. دوباره تلاش کنید یا به داشبورد برگردید.</p><div className="mt-5 flex flex-wrap gap-3"><button className="admin-button bg-slate-900 text-white" onClick={()=>this.setState({failed:false})}>تلاش مجدد</button><button className="admin-button" onClick={()=>navigate("/platform-admin")}>بازگشت به داشبورد</button></div></div></AdminLayout>;return this.props.children}
}

export function AdminUnavailable({retry,busy=false}){return <AdminLayout title="پنل مدیریت"><div className="rounded-2xl bg-white p-6 ring-1 ring-red-200"><h3 className="text-xl font-black text-red-700">ارتباط با سرور برقرار نشد</h3><p className="mt-3 leading-7 text-slate-600">لطفاً از فعال بودن سرور مطمئن شوید و دوباره تلاش کنید.</p><button disabled={busy} className="admin-button mt-5 bg-slate-900 text-white disabled:opacity-50" onClick={retry}>{busy?"در حال بررسی…":"تلاش مجدد"}</button></div></AdminLayout>}
