# Generated by Django 5.2.17 on 2026-08-28 21:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('default_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('unit', models.CharField(choices=[('item', 'عدد'), ('package', 'بسته'), ('carton', 'کارتن'), ('kilogram', 'کیلوگرم'), ('gram', 'گرم'), ('liter', 'لیتر'), ('meter', 'متر'), ('other', 'سایر')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
                'indexes': [models.Index(fields=['owner', 'is_active'], name='products_pr_owner_i_0d361b_idx'), models.Index(fields=['owner', 'name'], name='products_pr_owner_i_4e6ad6_idx')],
            },
        ),
    ]
